### PR TITLE
remove #[feature(alloc)], (stable since Rust 1.36)

### PR DESCRIPTION
**Pull request by daniel5151**

### CODE REVIEW

**Comment by daniel5151** [comment]
By the way, if it's not too much trouble, would it be possible to publish a new version of `managed` to crates.io?

I've had to copy the definition of `ManagedSlice` locally into my project ([`gdbstub`](https://github.com/daniel5151/gdbstub/)), but I'd much rather just use a dependency instead :smile:

**Comment by whitequark** [comment]
Does `#[feature(alloc)]` prevent you from using the latest release? I thought it would be a nop after the feature is stabilized...

**Comment by daniel5151** [comment]
It looks like the `#![feature]` attribute can't be used in stable Rust _at all_, regardless if the feature gets stabilized or not.
Here's a playground link: https://gist.github.com/29f0560e3e5899fdcdc7558c7e2eba92

**Comment by whitequark** [comment]
Gotcha, let me relelease it.

**Comment by whitequark** [comment]
Done https://crates.io/crates/managed/0.8.0

**Pull request merged**
